export const LEVELED_SNIPPETS: Record<string, { easy: string[], medium: string[], hard: string[] }> = {
  javascript: {
    easy: [
      "const sum = (a, b) => a + b;",
      "const name = 'CodeKey';",
      "let count = 0;",
      "if (x > 10) return true;",
      "console.log('Hello World');",
      "const arr = [1, 2, 3];",
      "let isActive = false;",
      "function greet(name) { return 'Hi'; }",
      "const x = 10 + 5;",
      "const obj = { a: 1 };",
      "arr.push(4);",
      "if (val) doSomething();",
      "return result || default;",
      "const isEmpty = !arr.length;",
      "x === y ? a : b;",
    ],
    medium: [
      "const filtered = array.filter(item => item.id !== id);",
      "export default function App() { return <div>Hello</div>; }",
      "const [state, setState] = useState(initialValue);",
      "document.getElementById('root').render(<App />);",
      "return numbers.reduce((acc, curr) => acc + curr, 0);",
      "const debounce = (fn, ms) => { let timeout; return (...args) => { ... }; };",
      "async function fetchData() { const res = await fetch(url); return res.json(); }",
      "const isValid = email && password.length >= 8;",
      "items.forEach(item => { console.log(item.name); });",
      "const sorted = arr.sort((a, b) => b.value - a.value);",
      "const unique = [...new Set(array)];",
      "try { execute(); } catch (e) { handleError(e); }",
      "const merged = { ...obj1, ...obj2 };",
      "element.addEventListener('click', handler);",
      "const formatted = num.toFixed(2);",
    ],
    hard: [
      "useEffect(() => { fetchData(); }, [dependency]);",
      "const { data, error } = useSWR('/api/user', fetcher);",
      "return await Promise.all(items.map(async i => process(i)));",
      "const pattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$/;",
      "export const getServerSideProps: GetServerSideProps = async (context) => { ... }",
      "const deepClone = obj => JSON.parse(JSON.stringify(obj));",
      "const memoized = useMemo(() => computeExpensive(a, b), [a, b]);",
      "const pipe = (...fns) => x => fns.reduce((v, f) => f(v), x);",
      "class EventEmitter { on(e, f) { ... } emit(e, ...a) { ... } }",
      "const curried = fn => a => b => fn(a, b);",
      "const compose = (...fns) => x => fns.reduceRight((v, f) => f(v), x);",
      "const lazy = (val, fn) => { let cache; return () => cache || (cache = fn()); };",
      "export default connect(mapStateToProps)(Component);",
      "const factory = (type) => new Map([['a', A], ['b', B]]).get(type);",
      "const createStore = (reducer, initial) => { let state = initial; return { ... }; };",
    ]
  },
  typescript: {
    easy: [
      "const x: number = 10;",
      "interface User { id: number; name: string; }",
      "function add(a: number, b: number): number { return a + b; }",
      "const isValid: boolean = true;",
      "type ID = string | number;",
      "const arr: string[] = [];",
      "enum Color { Red, Green }",
      "function greet(name: string): void { console.log(name); }",
      "type Status = 'pending' | 'active';",
      "const obj: Record<string, number> = {};",
      "interface Point { x: number; y: number; }",
      "function fn(x?: string): string | undefined { return x; }",
      "const isReadonly = true;",
      "type Maybe<T> = T | null;",
      "function identity<T>(arg: T): T { return arg; }",
    ],
    medium: [
      "type Callback = (data: string) => void;",
      "const getUser = (id: string): Promise<User> => { ... }",
      "enum Status { Pending, Active, Suspended }",
      "const result: Result<T, E> = await operation();",
      "interface Props extends React.HTMLAttributes<HTMLDivElement> {}",
      "type Partial<T> = { [P in keyof T]?: T[P] };",
      "function createContext<T>(initial: T): Context<T> { ... }",
      "const useState = <T>(initial: T): [T, (v: T) => void] => { ... };",
      "class Repository<T> { find(id: string): Promise<T | null> { ... } }",
      "interface Handler { (event: Event): void; }",
      "type Omit<T, K extends keyof T> = { [P in Exclude<keyof T, K>]: T[P] };",
      "const extract = <T extends object>(obj: T, keys: (keyof T)[]) => { ... };",
      "function pipe<T>(...fns: ((x: T) => T)[]): (x: T) => T { return x => ...; }",
      "interface Response<T> { data: T; status: number; ok: boolean; }",
      "type DeepReadonly<T> = { readonly [P in keyof T]: DeepReadonly<T[P]>; };",
    ],
    hard: [
      "export type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]>; };",
      "const withAuth = <P extends object>(Component: ComponentType<P>) => ...",
      "type ReturnType<T> = T extends (...args: any[]) => infer R ? R : any;",
      "interface GenericIdentityFn<T> { (arg: T): T; }",
      "class GenericNumber<T> { zeroValue: T; add: (x: T, y: T) => T; }",
      "type Merge<T, U> = { [P in keyof T | keyof U]: P extends keyof U ? U[P] : T[P]; };",
      "const createReducer = <S, A>(initial: S, handler: Handler<S, A>) => { ... };",
      "interface Deferred<T> { promise: Promise<T>; resolve: (v: T) => void; reject: (e: Error) => void; }",
      "type Flatten<T> = T extends Array<infer U> ? U : T;",
      "function compose<T>(...fns: ((x: T) => T)[]): (x: T) => T { return x => ...; }",
      "abstract class Base<T> { abstract execute(input: T): Promise<T>; }",
      "type Extract<T, U> = T extends U ? T : never;",
      "interface Builder<T> { build(): T; withName(n: string): Builder<T>; withAge(a: number): Builder<T>; }",
      "type Intersection<T, U> = T & U;",
      "const useReducer = <S, A>(reducer: Reducer<S, A>, init: S): [S, Dispatch<A>] => { ... };",
    ]
  },
  python: {
    easy: [
      "print('Hello World')",
      "x = 10",
      "def add(a, b):\n    return a + b",
      "items = [1, 2, 3]",
      "if x > 10:\n    print(x)",
      "name = 'Alice'",
      "is_valid = True",
      "for i in range(5):\n    print(i)",
      "d = {'key': 'value'}",
      "result = x * 2",
      "text = 'hello'.upper()",
      "nums = [1, 2, 3, 4, 5]",
      "if name == 'admin':\n    pass",
      "data = (1, 2, 3)",
      "value = x if x > 0 else 0",
    ],
    medium: [
      "def calculate_total(items):\n    return sum(item.price for item in items)",
      "class User(BaseModel):\n    id: int\n    username: str",
      "if __name__ == '__main__':\n    main()",
      "import pandas as pd\ndf = pd.read_csv('data.csv')",
      "squares = [x**2 for x in range(10)]",
      "result = list(filter(lambda x: x > 0, numbers))",
      "with open('file.txt', 'r') as f:\n    content = f.read()",
      "from typing import List, Optional, Dict",
      "data = {k: v for k, v in items if v}",
      "async def fetch_data():\n    async with aiohttp.ClientSession() as session:\n        async with session.get(url) as response:\n            return await response.json()",
      "try:\n    result = division(x, y)\nexcept ZeroDivisionError:\n    print('Error')",
      "def decorator(func):\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs)\n    return wrapper",
      "data = [(1, 'a'), (2, 'b')]\ndict(data)",
      "@dataclass\nclass Person:\n    name: str\n    age: int",
      "import numpy as np\narr = np.array([1, 2, 3])",
    ],
    hard: [
      "try:\n    response = requests.get(url)\nexcept Exception as e:\n    print(e)",
      "@app.route('/api/users', methods=['GET'])\ndef get_users():",
      "with open('file.txt', 'r') as f:\n    content = f.read()",
      "lambda x: x * 2 if x > 0 else 0",
      "class Meta(type):\n    def __new__(cls, name, bases, dct):",
      "def memoize(func):\n    cache = {}\n    def wrapper(*args):\n        if args not in cache:\n            cache[args] = func(*args)\n        return cache[args]\n    return wrapper",
      "from typing import Generic, TypeVar, Protocol\nT = TypeVar('T')\nclass Repository(Generic[T]):\n    def get(self, id: str) -> Optional[T]: ...",
      "async def main():\n    tasks = [process(i) for i in range(10)]\n    results = await asyncio.gather(*tasks)",
      "class Singleton:\n    _instance = None\n    def __new__(cls, *args, **kwargs):\n        if not cls._instance:\n            cls._instance = super().__new__(cls)\n        return cls._instance",
      "def chain(*funcs):\n    def apply(x):\n        for f in funcs:\n            x = f(x)\n        return x\n    return apply",
      "@property\ndef area(self):\n    return self._width * self._height",
      "from contextlib import contextmanager\n@contextmanager\ndef managed_resource():\n    resource = acquire()\n    try:\n        yield resource\n    finally:\n        release(resource)",
      "classLRUCache:\n    def __init__(self, capacity):\n        self.cache = OrderedDict()\n        self.capacity = capacity\n    def get(self, key): ...\n    def put(self, key, value): ...",
      "from itertools import islice, count\ndef fib():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\nfibs = islice(fib(), 10)",
      "def validate(schema, data):\n    errors = []\n    for field, rules in schema.items():\n        if rules.get('required') and field not in data:\n            errors.append(f'Missing {field}')\n    return errors",
    ]
  },
  cpp: {
    easy: [
      "int main() { return 0; }",
      "cout << \"Hello World\";",
      "int x = 10;",
      "string s = \"CodeKey\";",
      "if (x > 0) { return true; }",
      "vector<int> nums = {1, 2, 3};",
      "bool isValid = false;",
      "char grade = 'A';",
      "double pi = 3.14159;",
      "auto add = [](int a, int b) { return a + b; };",
      "const int MAX = 100;",
      "for (int i = 0; i < 10; i++) { }",
      "string name; cin >> name;",
      "int arr[5] = {1, 2, 3, 4, 5};",
      "void print() { }",
    ],
    medium: [
      "#include <iostream>\nusing namespace std;",
      "std::vector<int> numbers = {1, 2, 3, 4, 5};",
      "for (int i = 0; i < n; ++i) { sum += arr[i]; }",
      "class Shape { public: virtual void draw() = 0; };",
      "int* ptr = &x;",
      "std::string s = str.substr(0, 5);",
      "std::map<string, int> m; m[\"key\"] = 42;",
      "auto it = std::find(v.begin(), v.end(), target);",
      "std::sort(v.begin(), v.end(), [](int a, int b) { return a > b; });",
      "class Rectangle : public Shape { public: void draw() override; };",
      "std::unique_ptr<int> ptr(new int(42));",
      "try { throw std::runtime_error(\"Error\"); } catch (const std::exception& e) { }",
      "template<typename T> T max(T a, T b) { return a > b ? a : b; }",
      "std::queue<int> q; q.push(1); int x = q.front();",
      "namespace ns { void foo(); }",
    ],
    hard: [
      "template <typename T> T max(T a, T b) { return a > b ? a : b; }",
      "class Shape { virtual void draw() = 0; };",
      "auto lambda = [](int x, int y) { return x + y; };",
      "std::map<string, int> map;\nmap[\"key\"] = 10;",
      "unique_ptr<int> ptr(new int(5));",
      "std::thread t([](int x) { std::cout << x << std::endl; }, 42);",
      "std::future<int> fut = std::async(std::launch::async, task);",
      "template<class T> class Singleton { static T* instance; public: static T* get(); };",
      "std::variant<int, string, double> v; v = 42;",
      "std::optional<int> opt = std::nullopt;",
      "constexpr int factorial(int n) { return n <= 1 ? 1 : n * factorial(n - 1); }",
      "virtual void process() override { }",
      "std::unique_ptr<Base> ptr = std::make_unique<Derived>();",
      "std::unordered_map<string, vector<int>> graph;",
      "std::mutex mtx; std::lock_guard<std::mutex> lock(mtx);",
    ]
  },
  c: {
    easy: [
      "int main() { return 0; }",
      "printf(\"Hello, World!\\n\");",
      "int x = 10;",
      "char c = 'A';",
      "return x + y;",
      "int arr[5];",
      "float pi = 3.14f;",
      "if (x == y) { }",
      "for (int i = 0; i < n; i++) { }",
      "void foo() { }",
      "int* ptr = NULL;",
      "sizeof(int);",
      "const int MAX = 100;",
      "scanf(\"%d\", &x);",
      "return 0;",
    ],
    medium: [
      "for (int i = 0; i < 10; i++) { printf(\"%d\", i); }",
      "if (x > y) { return x; } else { return y; }",
      "int* ptr = &x;",
      "#include <stdio.h>\n#include <stdlib.h>",
      "void swap(int* a, int* b) { int t = *a; *a = *b; *b = t; }",
      "char* strcpy(char* dest, const char* src);",
      "int strlen(const char* s) { int len = 0; while (s[len]) len++; return len; }",
      "struct Point { int x; int y; };",
      "void* malloc(size_t size);",
      "FILE* fp = fopen(\"file.txt\", \"w\");",
      "typedef unsigned long ulong;",
      "enum { RED, GREEN, BLUE };",
      "union Data { int i; float f; char c; };",
      "void qsort(void* base, size_t nmemb, size_t size, int (*compar)(const void*, const void*));",
      "int atoi(const char* str);",
    ],
    hard: [
      "struct Node { int data; struct Node* next; };",
      "int* arr = (int*)malloc(n * sizeof(int));",
      "typedef struct { float x, y; } Point;",
      "while (*str) { hash = (hash << 5) + *str++; }",
      "FILE* fp = fopen(\"file.txt\", \"r\"); if (fp == NULL) exit(1);",
      "void* memcpy(void* dest, const void* src, size_t n) { char* d = dest; const char* s = src; while (n--) *d++ = *s++; }",
      "sigaction(SIGINT, &act, NULL);",
      "pthread_create(&thread, NULL, worker, NULL);",
      "sem_init(&sem, 0, 1);",
      "struct sigaction sa; sa.sa_handler = handler; sigemptyset(&sa.sa_mask);",
      "int bind(int sockfd, const struct sockaddr* addr, socklen_t addrlen);",
      "int select(int nfds, fd_set* readfds, fd_set* writefds, fd_set* exceptfds, struct timeval* timeout);",
      "void (*signal(int signum, void(*handler)(int)))(int);",
      "struct in_addr { uint32_t s_addr; };",
      "int ioctl(int fd, unsigned long request, ...);",
    ]
  },
  rust: {
    easy: [
      "fn main() { println!(\"Hello\"); }",
      "let x = 5;",
      "let mut y = 10;",
      "const MAX: i32 = 100;",
      "return true;",
      "let nums = vec![1, 2, 3];",
      "let name = String::from(\"Alice\");",
      "if x > 0 { }",
      "for i in 0..10 { }",
      "fn add(a: i32, b: i32) -> i32 { a + b }",
      "let s = \"hello\".to_string();",
      "match opt { Some(v) => v, None => 0, }",
      "use std::io;",
      "let pair = (1, \"hello\");",
      "#[allow(unused_variables)]",
    ],
    medium: [
      "let mut vec = Vec::new();\nvec.push(1);",
      "pub struct Point { x: f64, y: f64 }",
      "match x {\n    Some(v) => println!(\"{}\", v),\n    None => (),\n}",
      "for i in 0..5 { println!(\"{}\", i); }",
      "fn add(a: i32, b: i32) -> i32 { a + b }",
      "impl Rectangle {\n    pub fn area(&self) -> f64 { self.width * self.height }\n}",
      "let result: Result<i32, &str> = Ok(42);",
      "use std::collections::HashMap;",
      "fn split_at(self, mid: usize) -> (Vec<T>, Vec<T>) { ... }",
      "pub trait Draw { fn draw(&self); }",
      "let filtered: Vec<_> = nums.iter().filter(|x| *x > 0).collect();",
      "fn longest<'a>(x: &'a str, y: &'a str) -> &'a str { if x.len() > y.len() { x } else { y } }",
      "pub enum Message { Quit, Move { x: i32, y: i32 }, Write(String), }",
      "let _ = File::open(\"foo.txt\");",
      "unsafe fn dangerous() { }",
    ],
    hard: [
      "match result {\n    Ok(val) => println!(\"{}\", val),\n    Err(e) => eprintln!(\"{}\", e),\n}",
      "impl Display for Point { ... }",
      "pub fn spawn<F, T>(f: F) -> JoinHandle<T>",
      "use std::collections::HashMap;\nlet mut map = HashMap::new();",
      "#[derive(Debug, Clone, Copy)]\nstruct Unit;",
      "pub trait Iterator { type Item; fn next(&mut self) -> Option<Self::Item>; }",
      "impl<T> Vec<T> {\n    pub fn new() -> Self { vec![] }\n    pub fn push(&mut self, value: T) { ... }\n}",
      "unsafe extern \"C\" { fn abs(input: i32) -> i32; }",
      "macro_rules! assert_eq {\n    ($left:expr, $right:expr) => { ... };\n}",
      "pub struct RefCell<T> { ... }\nimpl<T> RefCell<T> { pub fn borrow(&self) -> Ref<T> { ... } }",
      "fn call_with<F, R>(f: F) -> R where F: FnOnce() -> R { f() }",
      "pub type Boxed<T> = Box<T, Global>;",
      "const fn factorial(n: u64) -> u64 { if n <= 1 { 1 } else { n * factorial(n - 1) } }",
      "pub trait IntoIterator { type Item; fn into_iter(self) -> Self::IntoIter; }",
      "struct Mutex<T> { data: UnsafeCell<T>, ... }",
    ]
  },
  go: {
    easy: [
      "fmt.Println(\"Hello\")",
      "var x int = 10",
      "func main() {}",
      "const Pi = 3.14",
      "return x + y",
      "var name string = \"Alice\"",
      "var isActive bool = true",
      "var nums []int = []int{1, 2, 3}",
      "m := make(map[string]int)",
      "if x > 0 { }",
      "for i := 0; i < 10; i++ { }",
      "type User struct { Name string }",
      "ch := make(chan int)",
      "defer fmt.Println(\"done\")",
      "go func() { }()",
    ],
    medium: [
      "func main() {\n\tfmt.Println(\"Hello, World!\")\n}",
      "type User struct {\n\tID   int\n\tName string\n}",
      "if err != nil {\n\treturn nil, err\n}",
      "for i := 0; i < 10; i++ {\n\tfmt.Println(i)\n}",
      "slice := []int{1, 2, 3}",
      "func add(a, b int) int { return a + b }",
      "err := json.Unmarshal(data, &v)",
      "wg := &sync.WaitGroup{}\nwg.Add(1)\ngo func() { defer wg.Done() }()",
      "func ReadFile(path string) ([]byte, error) { ... }",
      "defer func() { r := recover(); if r != nil { } }()",
      "case <-ch: fmt.Println(<-ch)",
      "mux := http.NewServeMux()\nmux.HandleFunc(\"/\", handler)",
      "rows, err := db.Query(\"SELECT * FROM users\")",
      "type Reader interface { Read(p []byte) (n int, err error) }",
      "func (u *User) String() string { return u.Name }",
    ],
    hard: [
      "go func() {\n\tch <- result\n}()",
      "for i, v := range slice {\n\tfmt.Println(i, v)\n}",
      "func (u *User) Save() error { ... }",
      "select {\ncase msg := <-c:\n\tfmt.Println(msg)\n}",
      "http.HandleFunc(\"/\", func(w http.ResponseWriter, r *http.Request) { ... })",
      "func worker(id int, jobs <-chan int, results chan<- int) { for j := range jobs { results <- j * 2 } }",
      "ctx, cancel := context.WithCancel(context.Background())\ndefer cancel()",
      "var buf bytes.Buffer\nbuf.WriteString(\"hello\")\nfmt.Println(buf.String())",
      "func merge(left, right []int) []int { ... }",
      "type Handler func(http.ResponseWriter, *http.Request)",
      "func (s *Server) Serve() error { ... }",
      "defer mu.Lock()\ndefer mu.Unlock()\ncounter++",
      "type Tree struct {\n\tVal int\n\tLeft *Tree\n\tRight *Tree\n}",
      "func quickSort(arr []int) []int { ... }",
      "func (p *Parser) parse() error { ... }",
    ]
  },
  warmup: {
    easy: [
      "asdf jkl;",
      "qwer uiop",
      "zxcv m,./",
      "1234 5678",
      "(){} []<>",
      "asdf jkl",
      "qwert yuiop",
      "zxcvbnm",
      "12345 67890",
      "as;ldkf j",
      "qwerty asdf",
      "zxcv qwer",
      "1qaz 2wsx",
      "1234 abcd",
      "[]{} /?'\"",
    ],
    medium: [
      "asdf jkl; asdf jkl;",
      "qwer uiop qwer uiop",
      "1234 5678 90-=",
      "!@#$ %^&*",
      "return true;",
      "const let var",
      "import export",
      "function return",
      "if else switch",
      "for while do",
      "class struct enum",
      "public private",
      "async await",
      "try catch finally",
      "interface type",
    ],
    hard: [
      "1234 5678 90-= 1234 5678 90-=",
      "!@#$ %^&* ()_+ !@#$ %^&* ()_+",
      "{ [ ( < > ) ] }",
      "const let var function return",
      "import export default from require",
      "public private protected static",
      "async await Promise then catch",
      "try catch finally throw error",
      "interface type class extends implements",
      "=> -> :: ?? || && | ^ ~ << >>",
      "function(arg) { return arg; }",
      "map.filter.reduce.forEach",
      "JSON.parse(JSON.stringify(obj))",
      "[].slice.call(arguments)",
      "Object.keys.values.entries",
    ]
  }
};
