export const LEVELED_SNIPPETS: Record<string, { easy: string[], medium: string[], hard: string[] }> = {
  javascript: {
    easy: [
      "const sum = (a, b) => a + b;",
      "const name = 'CodeKey';",
      "let count = 0;",
      "if (x > 10) return true;",
      "console.log('Hello World');",
      "const arr = [1, 2, 3];",
      "let isActive = false;",
      "function greet(name) { return 'Hi'; }",
      "const x = 10 + 5;",
      "const obj = { a: 1 };",
      "arr.push(4);",
      "if (val) doSomething();",
      "return result || default;",
      "const isEmpty = !arr.length;",
      "x === y ? a : b;",
    ],
    medium: [
      "const filtered = array.filter(item => item.id !== id);",
      "export default function App() { return <div>Hello</div>; }",
      "const [state, setState] = useState(initialValue);",
      "document.getElementById('root').render(<App />);",
      "return numbers.reduce((acc, curr) => acc + curr, 0);",
      "const debounce = (fn, ms) => { let timeout; return (...args) => { ... }; };",
      "async function fetchData() { const res = await fetch(url); return res.json(); }",
      "const isValid = email && password.length >= 8;",
      "items.forEach(item => { console.log(item.name); });",
      "const sorted = arr.sort((a, b) => b.value - a.value);",
      "const unique = [...new Set(array)];",
      "try { execute(); } catch (e) { handleError(e); }",
      "const merged = { ...obj1, ...obj2 };",
      "element.addEventListener('click', handler);",
      "const formatted = num.toFixed(2);",
    ],
    hard: [
      "useEffect(() => { fetchData(); }, [dependency]);",
      "const { data, error } = useSWR('/api/user', fetcher);",
      "return await Promise.all(items.map(async i => process(i)));",
      "const pattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$/;",
      "export const getServerSideProps: GetServerSideProps = async (context) => { ... }",
      "const deepClone = obj => JSON.parse(JSON.stringify(obj));",
      "const memoized = useMemo(() => computeExpensive(a, b), [a, b]);",
      "const pipe = (...fns) => x => fns.reduce((v, f) => f(v), x);",
      "class EventEmitter { on(e, f) { ... } emit(e, ...a) { ... } }",
      "const curried = fn => a => b => fn(a, b);",
      "const compose = (...fns) => x => fns.reduceRight((v, f) => f(v), x);",
      "const lazy = (val, fn) => { let cache; return () => cache || (cache = fn()); };",
      "export default connect(mapStateToProps)(Component);",
      "const factory = (type) => new Map([['a', A], ['b', B]]).get(type);",
      "const createStore = (reducer, initial) => { let state = initial; return { ... }; };",
    ]
  },
  typescript: {
    easy: [
      "const x: number = 10;",
      "interface User { id: number; name: string; }",
      "function add(a: number, b: number): number { return a + b; }",
      "const isValid: boolean = true;",
      "type ID = string | number;",
      "const arr: string[] = [];",
      "enum Color { Red, Green }",
      "function greet(name: string): void { console.log(name); }",
      "type Status = 'pending' | 'active';",
      "const obj: Record<string, number> = {};",
      "interface Point { x: number; y: number; }",
      "function fn(x?: string): string | undefined { return x; }",
      "const isReadonly = true;",
      "type Maybe<T> = T | null;",
      "function identity<T>(arg: T): T { return arg; }",
    ],
    medium: [
      "type Callback = (data: string) => void;",
      "const getUser = (id: string): Promise<User> => { ... }",
      "enum Status { Pending, Active, Suspended }",
      "const result: Result<T, E> = await operation();",
      "interface Props extends React.HTMLAttributes<HTMLDivElement> {}",
      "type Partial<T> = { [P in keyof T]?: T[P] };",
      "function createContext<T>(initial: T): Context<T> { ... }",
      "const useState = <T>(initial: T): [T, (v: T) => void] => { ... };",
      "class Repository<T> { find(id: string): Promise<T | null> { ... } }",
      "interface Handler { (event: Event): void; }",
      "type Omit<T, K extends keyof T> = { [P in Exclude<keyof T, K>]: T[P] };",
      "const extract = <T extends object>(obj: T, keys: (keyof T)[]) => { ... };",
      "function pipe<T>(...fns: ((x: T) => T)[]): (x: T) => T { return x => ...; }",
      "interface Response<T> { data: T; status: number; ok: boolean; }",
      "type DeepReadonly<T> = { readonly [P in keyof T]: DeepReadonly<T[P]>; };",
    ],
    hard: [
      "export type DeepPartial<T> = { [P in keyof T]?: DeepPartial<T[P]>; };",
      "const withAuth = <P extends object>(Component: ComponentType<P>) => ...",
      "type ReturnType<T> = T extends (...args: any[]) => infer R ? R : any;",
      "interface GenericIdentityFn<T> { (arg: T): T; }",
      "class GenericNumber<T> { zeroValue: T; add: (x: T, y: T) => T; }",
      "type Merge<T, U> = { [P in keyof T | keyof U]: P extends keyof U ? U[P] : T[P]; };",
      "const createReducer = <S, A>(initial: S, handler: Handler<S, A>) => { ... };",
      "interface Deferred<T> { promise: Promise<T>; resolve: (v: T) => void; reject: (e: Error) => void; }",
      "type Flatten<T> = T extends Array<infer U> ? U : T;",
      "function compose<T>(...fns: ((x: T) => T)[]): (x: T) => T { return x => ...; }",
      "abstract class Base<T> { abstract execute(input: T): Promise<T>; }",
      "type Extract<T, U> = T extends U ? T : never;",
      "interface Builder<T> { build(): T; withName(n: string): Builder<T>; withAge(a: number): Builder<T>; }",
      "type Intersection<T, U> = T & U;",
      "const useReducer = <S, A>(reducer: Reducer<S, A>, init: S): [S, Dispatch<A>] => { ... };",
    ]
  },
  python: {
    easy: [
      "print('Hello World')",
      "x = 10",
      "def add(a, b):\n    return a + b",
      "items = [1, 2, 3]",
      "if x > 10:\n    print(x)",
      "name = 'Alice'",
      "is_valid = True",
      "for i in range(5):\n    print(i)",
      "d = {'key': 'value'}",
      "result = x * 2",
      "text = 'hello'.upper()",
      "nums = [1, 2, 3, 4, 5]",
      "if name == 'admin':\n    pass",
      "data = (1, 2, 3)",
      "value = x if x > 0 else 0",
    ],
    medium: [
      "def calculate_total(items):\n    return sum(item.price for item in items)",
      "class User(BaseModel):\n    id: int\n    username: str",
      "if __name__ == '__main__':\n    main()",
      "import pandas as pd\ndf = pd.read_csv('data.csv')",
      "squares = [x**2 for x in range(10)]",
      "result = list(filter(lambda x: x > 0, numbers))",
      "with open('file.txt', 'r') as f:\n    content = f.read()",
      "from typing import List, Optional, Dict",
      "data = {k: v for k, v in items if v}",
      "async def fetch_data():\n    async with aiohttp.ClientSession() as session:\n        async with session.get(url) as response:\n            return await response.json()",
      "try:\n    result = division(x, y)\nexcept ZeroDivisionError:\n    print('Error')",
      "def decorator(func):\n    def wrapper(*args, **kwargs):\n        return func(*args, **kwargs)\n    return wrapper",
      "data = [(1, 'a'), (2, 'b')]\ndict(data)",
      "@dataclass\nclass Person:\n    name: str\n    age: int",
      "import numpy as np\narr = np.array([1, 2, 3])",
    ],
    hard: [
      "try:\n    response = requests.get(url)\nexcept Exception as e:\n    print(e)",
      "@app.route('/api/users', methods=['GET'])\ndef get_users():",
      "with open('file.txt', 'r') as f:\n    content = f.read()",
      "lambda x: x * 2 if x > 0 else 0",
      "class Meta(type):\n    def __new__(cls, name, bases, dct):",
      "def memoize(func):\n    cache = {}\n    def wrapper(*args):\n        if args not in cache:\n            cache[args] = func(*args)\n        return cache[args]\n    return wrapper",
      "from typing import Generic, TypeVar, Protocol\nT = TypeVar('T')\nclass Repository(Generic[T]):\n    def get(self, id: str) -> Optional[T]: ...",
      "async def main():\n    tasks = [process(i) for i in range(10)]\n    results = await asyncio.gather(*tasks)",
      "class Singleton:\n    _instance = None\n    def __new__(cls, *args, **kwargs):\n        if not cls._instance:\n            cls._instance = super().__new__(cls)\n        return cls._instance",
      "def chain(*funcs):\n    def apply(x):\n        for f in funcs:\n            x = f(x)\n        return x\n    return apply",
      "@property\ndef area(self):\n    return self._width * self._height",
      "from contextlib import contextmanager\n@contextmanager\ndef managed_resource():\n    resource = acquire()\n    try:\n        yield resource\n    finally:\n        release(resource)",
      "classLRUCache:\n    def __init__(self, capacity):\n        self.cache = OrderedDict()\n        self.capacity = capacity\n    def get(self, key): ...\n    def put(self, key, value): ...",
      "from itertools import islice, count\ndef fib():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\nfibs = islice(fib(), 10)",
      "def validate(schema, data):\n    errors = []\n    for field, rules in schema.items():\n        if rules.get('required') and field not in data:\n            errors.append(f'Missing {field}')\n    return errors",
    ]
  },
  cpp: {
    easy: [
      "int main() { return 0; }",
      "cout << \"Hello World\";",
      "int x = 10;",
      "string s = \"CodeKey\";",
      "if (x > 0) { return true; }",
      "vector<int> nums = {1, 2, 3};",
      "bool isValid = false;",
      "char grade = 'A';",
      "double pi = 3.14159;",
      "auto add = [](int a, int b) { return a + b; };",
      "const int MAX = 100;",
      "for (int i = 0; i < 10; i++) { }",
      "string name; cin >> name;",
      "int arr[5] = {1, 2, 3, 4, 5};",
      "void print() { }",
    ],
    medium: [
      "#include <iostream>\nusing namespace std;",
      "std::vector<int> numbers = {1, 2, 3, 4, 5};",
      "for (int i = 0; i < n; ++i) { sum += arr[i]; }",
      "class Shape { public: virtual void draw() = 0; };",
      "int* ptr = &x;",
      "std::string s = str.substr(0, 5);",
      "std::map<string, int> m; m[\"key\"] = 42;",
      "auto it = std::find(v.begin(), v.end(), target);",
      "std::sort(v.begin(), v.end(), [](int a, int b) { return a > b; });",
      "class Rectangle : public Shape { public: void draw() override; };",
      "std::unique_ptr<int> ptr(new int(42));",
      "try { throw std::runtime_error(\"Error\"); } catch (const std::exception& e) { }",
      "template<typename T> T max(T a, T b) { return a > b ? a : b; }",
      "std::queue<int> q; q.push(1); int x = q.front();",
      "namespace ns { void foo(); }",
    ],
    hard: [
      "template <typename T> T max(T a, T b) { return a > b ? a : b; }",
      "class Shape { virtual void draw() = 0; };",
      "auto lambda = [](int x, int y) { return x + y; };",
      "std::map<string, int> map;\nmap[\"key\"] = 10;",
      "unique_ptr<int> ptr(new int(5));",
      "std::thread t([](int x) { std::cout << x << std::endl; }, 42);",
      "std::future<int> fut = std::async(std::launch::async, task);",
      "template<class T> class Singleton { static T* instance; public: static T* get(); };",
      "std::variant<int, string, double> v; v = 42;",
      "std::optional<int> opt = std::nullopt;",
      "constexpr int factorial(int n) { return n <= 1 ? 1 : n * factorial(n - 1); }",
      "virtual void process() override { }",
      "std::unique_ptr<Base> ptr = std::make_unique<Derived>();",
      "std::unordered_map<string, vector<int>> graph;",
      "std::mutex mtx; std::lock_guard<std::mutex> lock(mtx);",
    ]
  },
  c: {
    easy: [
      "int main() { return 0; }",
      "printf(\"Hello, World!\\n\");",
      "int x = 10;",
      "char c = 'A';",
      "return x + y;",
      "int arr[5];",
      "float pi = 3.14f;",
      "if (x == y) { }",
      "for (int i = 0; i < n; i++) { }",
      "void foo() { }",
      "int* ptr = NULL;",
      "sizeof(int);",
      "const int MAX = 100;",
      "scanf(\"%d\", &x);",
      "return 0;",
    ],
    medium: [
      "for (int i = 0; i < 10; i++) { printf(\"%d\", i); }",
      "if (x > y) { return x; } else { return y; }",
      "int* ptr = &x;",
      "#include <stdio.h>\n#include <stdlib.h>",
      "void swap(int* a, int* b) { int t = *a; *a = *b; *b = t; }",
      "char* strcpy(char* dest, const char* src);",
      "int strlen(const char* s) { int len = 0; while (s[len]) len++; return len; }",
      "struct Point { int x; int y; };",
      "void* malloc(size_t size);",
      "FILE* fp = fopen(\"file.txt\", \"w\");",
      "typedef unsigned long ulong;",
      "enum { RED, GREEN, BLUE };",
      "union Data { int i; float f; char c; };",
      "void qsort(void* base, size_t nmemb, size_t size, int (*compar)(const void*, const void*));",
      "int atoi(const char* str);",
    ],
    hard: [
      "struct Node { int data; struct Node* next; };",
      "int* arr = (int*)malloc(n * sizeof(int));",
      "typedef struct { float x, y; } Point;",
      "while (*str) { hash = (hash << 5) + *str++; }",
      "FILE* fp = fopen(\"file.txt\", \"r\"); if (fp == NULL) exit(1);",
      "void* memcpy(void* dest, const void* src, size_t n) { char* d = dest; const char* s = src; while (n--) *d++ = *s++; }",
      "sigaction(SIGINT, &act, NULL);",
      "pthread_create(&thread, NULL, worker, NULL);",
      "sem_init(&sem, 0, 1);",
      "struct sigaction sa; sa.sa_handler = handler; sigemptyset(&sa.sa_mask);",
      "int bind(int sockfd, const struct sockaddr* addr, socklen_t addrlen);",
      "int select(int nfds, fd_set* readfds, fd_set* writefds, fd_set* exceptfds, struct timeval* timeout);",
      "void (*signal(int signum, void(*handler)(int)))(int);",
      "struct in_addr { uint32_t s_addr; };",
      "int ioctl(int fd, unsigned long request, ...);",
    ]
  },
  rust: {
    easy: [
      "fn main() { println!(\"Hello\"); }",
      "let x = 5;",
      "let mut y = 10;",
      "const MAX: i32 = 100;",
      "return true;",
      "let nums = vec![1, 2, 3];",
      "let name = String::from(\"Alice\");",
      "if x > 0 { }",
      "for i in 0..10 { }",
      "fn add(a: i32, b: i32) -> i32 { a + b }",
      "let s = \"hello\".to_string();",
      "match opt { Some(v) => v, None => 0, }",
      "use std::io;",
      "let pair = (1, \"hello\");",
      "#[allow(unused_variables)]",
    ],
    medium: [
      "let mut vec = Vec::new();\nvec.push(1);",
      "pub struct Point { x: f64, y: f64 }",
      "match x {\n    Some(v) => println!(\"{}\", v),\n    None => (),\n}",
      "for i in 0..5 { println!(\"{}\", i); }",
      "fn add(a: i32, b: i32) -> i32 { a + b }",
      "impl Rectangle {\n    pub fn area(&self) -> f64 { self.width * self.height }\n}",
      "let result: Result<i32, &str> = Ok(42);",
      "use std::collections::HashMap;",
      "fn split_at(self, mid: usize) -> (Vec<T>, Vec<T>) { ... }",
      "pub trait Draw { fn draw(&self); }",
      "let filtered: Vec<_> = nums.iter().filter(|x| *x > 0).collect();",
      "fn longest<'a>(x: &'a str, y: &'a str) -> &'a str { if x.len() > y.len() { x } else { y } }",
      "pub enum Message { Quit, Move { x: i32, y: i32 }, Write(String), }",
      "let _ = File::open(\"foo.txt\");",
      "unsafe fn dangerous() { }",
    ],
    hard: [
      "match result {\n    Ok(val) => println!(\"{}\", val),\n    Err(e) => eprintln!(\"{}\", e),\n}",
      "impl Display for Point { ... }",
      "pub fn spawn<F, T>(f: F) -> JoinHandle<T>",
      "use std::collections::HashMap;\nlet mut map = HashMap::new();",
      "#[derive(Debug, Clone, Copy)]\nstruct Unit;",
      "pub trait Iterator { type Item; fn next(&mut self) -> Option<Self::Item>; }",
      "impl<T> Vec<T> {\n    pub fn new() -> Self { vec![] }\n    pub fn push(&mut self, value: T) { ... }\n}",
      "unsafe extern \"C\" { fn abs(input: i32) -> i32; }",
      "macro_rules! assert_eq {\n    ($left:expr, $right:expr) => { ... };\n}",
      "pub struct RefCell<T> { ... }\nimpl<T> RefCell<T> { pub fn borrow(&self) -> Ref<T> { ... } }",
      "fn call_with<F, R>(f: F) -> R where F: FnOnce() -> R { f() }",
      "pub type Boxed<T> = Box<T, Global>;",
      "const fn factorial(n: u64) -> u64 { if n <= 1 { 1 } else { n * factorial(n - 1) } }",
      "pub trait IntoIterator { type Item; fn into_iter(self) -> Self::IntoIter; }",
      "struct Mutex<T> { data: UnsafeCell<T>, ... }",
    ]
  },
  go: {
    easy: [
      "fmt.Println(\"Hello\")",
      "var x int = 10",
      "func main() {}",
      "const Pi = 3.14",
      "return x + y",
      "var name string = \"Alice\"",
      "var isActive bool = true",
      "var nums []int = []int{1, 2, 3}",
      "m := make(map[string]int)",
      "if x > 0 { }",
      "for i := 0; i < 10; i++ { }",
      "type User struct { Name string }",
      "ch := make(chan int)",
      "defer fmt.Println(\"done\")",
      "go func() { }()",
    ],
    medium: [
      "func main() {\n\tfmt.Println(\"Hello, World!\")\n}",
      "type User struct {\n\tID   int\n\tName string\n}",
      "if err != nil {\n\treturn nil, err\n}",
      "for i := 0; i < 10; i++ {\n\tfmt.Println(i)\n}",
      "slice := []int{1, 2, 3}",
      "func add(a, b int) int { return a + b }",
      "err := json.Unmarshal(data, &v)",
      "wg := &sync.WaitGroup{}\nwg.Add(1)\ngo func() { defer wg.Done() }()",
      "func ReadFile(path string) ([]byte, error) { ... }",
      "defer func() { r := recover(); if r != nil { } }()",
      "case <-ch: fmt.Println(<-ch)",
      "mux := http.NewServeMux()\nmux.HandleFunc(\"/\", handler)",
      "rows, err := db.Query(\"SELECT * FROM users\")",
      "type Reader interface { Read(p []byte) (n int, err error) }",
      "func (u *User) String() string { return u.Name }",
    ],
    hard: [
      "go func() {\n\tch <- result\n}()",
      "for i, v := range slice {\n\tfmt.Println(i, v)\n}",
      "func (u *User) Save() error { ... }",
      "select {\ncase msg := <-c:\n\tfmt.Println(msg)\n}",
      "http.HandleFunc(\"/\", func(w http.ResponseWriter, r *http.Request) { ... })",
      "func worker(id int, jobs <-chan int, results chan<- int) { for j := range jobs { results <- j * 2 } }",
      "ctx, cancel := context.WithCancel(context.Background())\ndefer cancel()",
      "var buf bytes.Buffer\nbuf.WriteString(\"hello\")\nfmt.Println(buf.String())",
      "func merge(left, right []int) []int { ... }",
      "type Handler func(http.ResponseWriter, *http.Request)",
      "func (s *Server) Serve() error { ... }",
      "defer mu.Lock()\ndefer mu.Unlock()\ncounter++",
      "type Tree struct {\n\tVal int\n\tLeft *Tree\n\tRight *Tree\n}",
      "func quickSort(arr []int) []int { ... }",
      "func (p *Parser) parse() error { ... }",
    ]
  },
  warmup: {
    easy: [
      "asdf jkl;",
      "qwer uiop",
      "zxcv m,./",
      "1234 5678",
      "(){} []<>",
      "asdf jkl",
      "qwert yuiop",
      "zxcvbnm",
      "12345 67890",
      "as;ldkf j",
      "qwerty asdf",
      "zxcv qwer",
      "1qaz 2wsx",
      "1234 abcd",
      "[]{} /?'\"",
    ],
    medium: [
      "asdf jkl; asdf jkl;",
      "qwer uiop qwer uiop",
      "1234 5678 90-=",
      "!@#$ %^&*",
      "return true;",
      "const let var",
      "import export",
      "function return",
      "if else switch",
      "for while do",
      "class struct enum",
      "public private",
      "async await",
      "try catch finally",
      "interface type",
    ],
    hard: [
      "1234 5678 90-= 1234 5678 90-=",
      "!@#$ %^&* ()_+ !@#$ %^&* ()_+",
      "{ [ ( < > ) ] }",
      "const let var function return",
      "import export default from require",
      "public private protected static",
      "async await Promise then catch",
      "try catch finally throw error",
      "interface type class extends implements",
      "=> -> :: ?? || && | ^ ~ << >>",
      "function(arg) { return arg; }",
      "map.filter.reduce.forEach",
      "JSON.parse(JSON.stringify(obj))",
      "[].slice.call(arguments)",
      "Object.keys.values.entries",
    ]
  },
  java: {
    easy: [
      "public static void main(String[] args) {}",
      "int x = 10;",
      "String name = \"Hello\";",
      "boolean isActive = true;",
      "System.out.println(\"Hello\");",
      "List<String> list = new ArrayList<>();",
      "if (x > 0) { }",
      "for (int i = 0; i < 10; i++) { }",
      "return x + y;",
      "private int count;",
      "public class Main { }",
      "void method() { }",
      "final int MAX = 100;",
      "double pi = 3.14;",
      "char grade = 'A';",
    ],
    medium: [
      "public static <T> T identity(T value) { return value; }",
      "List<Integer> nums = Arrays.asList(1, 2, 3);",
      "@Override\npublic void run() { }",
      "Map<String, Integer> map = new HashMap<>();",
      "Optional<String> opt = Optional.ofNullable(value);",
      "public void sort(int[] arr) { Arrays.sort(arr); }",
      "try (FileReader fr = new FileReader(file)) { }",
      "Stream.of(a, b, c).filter(x -> x > 0).collect(toList());",
      "public interface Repository<T> { T findById(String id); }",
      "@Autowired\nprivate Service service;",
      "public class User implements Serializable { }",
      "String result = list.stream().map(String::toUpperCase).collect(joining(\",\"));",
      "CompletableFuture.supplyAsync(() -> process());",
      "@Entity\n@Table(name = \"users\")\npublic class User { }",
      "Predicate<String> isEmpty = String::isBlank;",
    ],
    hard: [
      "public <T extends Comparable<T>> void sort(List<T> list) { Collections.sort(list); }",
      "@Component\npublic class UserService implements UserDetailsService { ... }",
      "public Mono<ResponseEntity<Resource>> download(@PathVariable String id) { ... }",
      "public class Builder<T> { public T build() { return instance; } }",
      "@Transactional(isolation = Isolation.SERIALIZABLE)\npublic void process() { }",
      "public CompletableFuture<T> withTimeout(long timeout, TimeUnit unit) { ... }",
      "public class Cache<K, V> implements CacheLoader<K, V> { ... }",
      "@Scheduled(cron = \"0 0 * * * *\")\npublic void cleanup() { }",
      "public <T, R> Function<T, R> compose(Function<T, T> before, Function<T, R> after) { ... }",
      "public class EventListener implements ApplicationListener<ApplicationReadyEvent> { ... }",
      "@Configuration\n@EnableWebSecurity\npublic class SecurityConfig extends WebSecurityConfigurerAdapter { ... }",
      "public Flux<T> stream(Duration interval) { return Flux.interval(interval); }",
      "public Optional<Repository<T>> findBySpecification(Specification<T> spec) { ... }",
      "public class DaoImpl<T> extends JpaRepository<T, Long> implements CustomDao<T> { ... }",
      "@Aspect\n@Component\npublic class LoggingAspect { @Before(\"execution(* *..*.*(..))\") }",
    ]
  },
  csharp: {
    easy: [
      "Console.WriteLine(\"Hello\");",
      "int x = 10;",
      "string name = \"Alice\";",
      "bool isActive = true;",
      "var list = new List<int>();",
      "if (x > 0) { }",
      "for (int i = 0; i < 10; i++) { }",
      "public class User { }",
      "private int count;",
      "return x + y;",
      "var dict = new Dictionary<string, int>();",
      "async Task RunAsync() { }",
      "const int Max = 100;",
      "double pi = 3.14;",
      "var result = list.FirstOrDefault();",
    ],
    medium: [
      "public async Task<T> GetAsync<T>(string url) { var res = await client.GetAsync(url); return await res.Content.ReadAsAsync<T>(); }",
      "var query = users.Where(u => u.Age > 18).OrderBy(u => u.Name).Select(u => new { u.Id, u.Name });",
      "using (var context = new DbContext()) { var user = await context.Users.FindAsync(id); }",
      "public IActionResult GetUser(int id) => Ok(new { Id = id, Name = \"Test\" });",
      "var items = await Task.WhenAll(tasks.Select(t => t.Result));",
      "[HttpGet(\"{id}\")]\npublic async Task<ActionResult<User>> GetUser(int id) { ... }",
      "public class UserService : IUserService { private readonly IRepository<User> _repo; }",
      "var result = list.Aggregate((a, b) => a + b);",
      "[Authorize(Roles = \"Admin\")]\npublic IActionResult AdminOnly() { }",
      "public void ConfigureServices(IServiceCollection services) { services.AddScoped<IRepo, Repo>(); }",
      "public class Mapper : Profile { public Mapper() { CreateMap<User, UserDto>(); } }",
      "var cached = _memoryCache.GetOrCreate(key, entry => { entry.SlidingExpiration = TimeSpan.FromMinutes(10); return data; });",
      "[Route(\"api/[controller]\")]\n[ApiController]\npublic class UsersController : ControllerBase { }",
      "public static string ToJson<T>(this T obj) => JsonSerializer.Serialize(obj);",
      "var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };",
    ],
    hard: [
      "public class Repository<T> : IRepository<T> where T : class { private readonly DbContext _context; }",
      "public async IAsyncEnumerable<T> StreamAsync<T>([EnumeratorCancellation] CancellationToken ct) { ... }",
      "public class Middleware { public async Task InvokeAsync(HttpContext context, RequestDelegate next) { ... } }",
      "public class ExpressionVisitor : ExpressionVisitor<T> { protected override Expression VisitLambda<T>(Expression<T> node) { ... } }",
      "[DbFunction(\"dbo\", \"MyFunction\")]\npublic static int MyFunction(string param) => throw new Exception();",
      "public class QueryHandler<TQuery, TResult> : IRequestHandler<TQuery, TResult> where TQuery : IRequest<TResult> { }",
      "public class PollyPolicy { public static IAsyncPolicy<HttpResponseMessage> RetryPolicy() { return Policy.Handle<HttpException>().RetryAsync(3); } }",
      "public class SignalRHub : Hub<IHubClient> { public async Task SendMessage(string user, string message) { await Clients.All.ReceiveMessage(user, message); } }",
      "public class DynamicLinq : IDisposable { public IQueryable<T> Query<T>(string filter) { return _context.Set<T>().Where(filter); } }",
      "[Test]\n[Theory]\n[InlineData(1, 2, 3)]\npublic void Test(int a, int b, int expected) { Assert.Equal(expected, a + b); }",
      "public class ODataController : ODataController { [EnableQuery] public IQueryable<Item> Get() { return _db.Items; } }",
      "public class Worker : BackgroundService { protected override async Task ExecuteAsync(CancellationToken stoppingToken) { while (!stoppingToken.IsCancellationRequested) { } } }",
      "public class GraphQLMiddleware { public async Task ResolveAsync(ResolveFieldContext context) { var result = await _service.QueryAsync(context); } }",
      "public class EFUnitOfWork : IUnitOfWork { public IRepository<T> GetRepository<T>() where T : class { return new Repository<T>(_db); } }",
      "[DataContract]\npublic class DataContract<T> : IExtensibleDataObject { ExtensionDataObject ExtensionData { get; set; } }",
    ]
  },
  ruby: {
    easy: [
      "puts \"Hello World\"",
      "x = 10",
      "name = \"Alice\"",
      "is_active = true",
      "[1, 2, 3].each { |i| puts i }",
      "if x > 10\n  puts \"big\"\nend",
      "5.times { |i| puts i }",
      "def add(a, b)\n    a + b\nend",
      "hash = { key: \"value\" }",
      "arr = [1, 2, 3]",
      "class User\nend",
      "attr_accessor :name",
      "module Helper\nend",
      "require 'json'",
      "nil || \"default\"",
    ],
    medium: [
      "users.select { |u| u.admin? }.map(&:name)",
      "class User < ApplicationRecord\n  validates :email, presence: true\nend",
      "def create_user(params)\n  User.create!(params)\nrescue ActiveRecord::RecordInvalid => e\n  render json: { error: e.message }\nend",
      "posts = Post.where('created_at > ?', 1.week.ago).order(created_at: :desc)",
      "module Api\n    class UsersController < ApplicationController\n      def index\n        render json: User.all\n      end\n    end\n  end",
      "data = JSON.parse(response.body, symbolize_names: true)",
      "Thread.new { perform_background_task }.join",
      "class_eval(\"def #{name}; @#{name}; end\")",
      "before_action :authenticate_user!, only: [:edit, :update]",
      "has_many :posts, foreign_key: :author_id, class_name: 'Post'",
      "ActiveJob::Base.queue_adapter = :sidekiq\n  Sidekiq::Worker.async: true",
      "include Enumerable\n  def each(&block)\n    @items.each(&block)\n  end",
      "Rails.application.routes.draw do\n    resources :users do\n      member { get :profile }\n    end\n  end",
      "class Dog\n    extend ActiveModel::Naming\n    include ActiveModel::Conversion\n  end",
      "scope :active, -> { where(active: true).where('created_at > ?', 30.days.ago) }",
    ],
    hard: [
      "class Service\n  include Singleton\n  include Callable\n  extend ActiveModel::Naming\n  def call\n    perform\n  end\nend",
      "ActiveRecord::Base.transaction do\n  account.withdraw(amount)\n  AuditLog.create!(user: current_user, action: 'withdraw', amount: amount)\nend",
      "class GraphQL::Schema::Object < GraphQL::SchemaObject\n  field :users, [UserType], null: false\n  def users\n    User.all\n  end\nend",
      "class Sidekiq::Worker\n  include Sidekiq::Worker\n  sidekiq_options queue: :critical, retry: 5\n  def perform(user_id, data)\n    UserMailer.send_digest(user_id, data).deliver_now\n  end\nend",
      "RSpec.describe User do\n  let(:user) { User.new(name: 'Alice') }\n  it 'is valid' do\n    expect(user).to be_valid\n  end\nend",
      "class Macro\n    def self.included(base)\n      base.extend(ClassMethods)\n      base.include(InstanceMethods)\n    end\n  end",
      "ActiveSupport.on_load(:active_record) do\n    belongs_to :user, touch: true, counter_cache: true\n  end",
      "class Middleware\n    def initialize(app)\n      @app = app\n    end\n    def call(env)\n      # Process request\n      @app.call(env)\n    end\n  end",
      "FactoryBot.define do\n    factory :user do\n      sequence(:email) { |n| \"user#{n}@example.com\" }\n      password { 'password123' }\n      trait :admin do\n        role { 'admin' }\n      end\n    end\n  end",
      "Pry.config.commands.create_command 'my-command' do\n    description 'Does something cool'\n    process { |arg| puts \"Result: #{arg}\" }\n  end",
      "Module.new do\n    def self.included(base)\n      base.extend(ClassMethods)\n      base.class_eval { attr_accessor :config }\n    end\n  end",
      "Rake::Task['db:migrate'].invoke\n  Rake::Task['db:seed'].execute",
      "class ActiveJob::Performer\n    retry_on StandardError, wait: :exponentially_longer, attempts: 5\n  end",
      "ActiveStorage.attachables.each do |attachable|\n    define_method(\"attach_#{attachable.name}\") { |attachable }\n  end",
      "Marshal.dump(obj, File.open(file, 'wb'))\n  Marshal.load(File.open(file, 'rb'))",
    ]
  },
  sql: {
    easy: [
      "SELECT * FROM users;",
      "SELECT name, email FROM users;",
      "WHERE id = 1;",
      "INSERT INTO users (name) VALUES ('Alice');",
      "UPDATE users SET active = true;",
      "DELETE FROM users WHERE id = 1;",
      "ORDER BY name ASC;",
      "LIMIT 10;",
      "COUNT(*);",
      "WHERE age > 18;",
      "DISTINCT category;",
      "GROUP BY status;",
      "HAVING COUNT(*) > 5;",
      "AS u FROM users u;",
      "IN ('a', 'b', 'c');",
    ],
    medium: [
      "SELECT u.name, COUNT(o.id) as orders FROM users u LEFT JOIN orders o ON u.id = o.user_id GROUP BY u.id;",
      "SELECT * FROM products WHERE price BETWEEN 10 AND 100 ORDER BY price DESC LIMIT 20;",
      "CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100), email VARCHAR(255) UNIQUE);",
      "INSERT INTO logs (user_id, action, created_at) SELECT id, 'login', NOW() FROM users WHERE active = true;",
      "UPDATE users SET last_login = NOW(), login_count = login_count + 1 WHERE id = ?;",
      "WITH cte AS (SELECT id, name FROM users WHERE active = true) SELECT * FROM cte;",
      "SELECT DATE_TRUNC('day', created_at) as day, COUNT(*) FROM events GROUP BY day;",
      "CREATE INDEX idx_users_email ON users(email) WHERE email IS NOT NULL;",
      "SELECT p.*, c.name as category FROM products p JOIN categories c ON p.category_id = c.id;",
      "DELETE FROM sessions WHERE created_at < NOW() - INTERVAL '30 days';",
      "ALTER TABLE users ADD COLUMN phone VARCHAR(20) DEFAULT NULL;",
      "GRANT SELECT, INSERT ON users TO app_user; REVOKE DELETE ON users FROM app_user;",
      "SELECT * FROM users WHERE name ILIKE '%john%' OR email ILIKE '%john%';",
      "EXPLAIN ANALYZE SELECT * FROM orders WHERE user_id = 1 AND status = 'pending';",
      "UPSERT INTO users (id, name, updated_at) VALUES (1, 'Alice', NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;",
    ],
    hard: [
      "WITH RECURSIVE org_chart AS (SELECT id, name, manager_id, 1 as level FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.id, e.name, e.manager_id, oc.level + 1 FROM employees e JOIN org_chart oc ON e.manager_id = oc.id) SELECT * FROM org_chart;",
      "SELECT u.*, p.*, ROW_NUMBER() OVER (PARTITION BY u.id ORDER BY p.created_at DESC) as rn FROM users u JOIN posts p ON u.id = p.user_id WHERE p.status = 'published';",
      "CREATE OR REPLACE FUNCTION update_updated_at() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$ LANGUAGE plpgsql; CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at();",
      "INSERT INTO audit_log (table_name, record_id, action, old_data, new_data, changed_by, changed_at) VALUES ('users', OLD.id, 'UPDATE', row_to_json(OLD), row_to_json(NEW), current_user, NOW());",
      "SELECT g.id, g.name, array_agg(DISTINCT t.name) as tags FROM groups g LEFT JOIN group_tags gt ON g.id = gt.group_id LEFT JOIN tags t ON gt.tag_id = t.id GROUP BY g.id HAVING COUNT(DISTINCT t.id) >= 3;",
      "CREATE MATERIALIZED VIEW monthly_sales AS SELECT DATE_TRUNC('month', created_at) as month, SUM(amount) as total, COUNT(*) as orders FROM orders WHERE status = 'completed' WITH DATA; REFRESH MATERIALIZED VIEW CONCURRENTLY monthly_sales;",
      "DO $$ DECLARE rec record; BEGIN FOR rec IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP EXECUTE 'GRANT SELECT ON ' || rec.tablename || ' TO readonly_user'; END LOOP; END $$;",
      "SELECT query, calls, total_exec_time, mean_exec_time, rows, 100.0 * shared_blks_hit / NULLIF(shared_blks_hit + shared_blks_read, 0) as hit_ratio FROM pg_stat_statements WHERE query LIKE '%users%' ORDER BY total_exec_time DESC LIMIT 10;",
      "CREATE DOMAIN email AS VARCHAR(255) CHECK (VALUE ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'); CREATE TYPE status_enum AS ENUM ('pending', 'active', 'completed');",
      "WITH summary AS (SELECT department, SUM(salary) as total FROM employees GROUP BY department HAVING SUM(salary) > 100000) SELECT e.*, s.total as dept_total FROM employees e JOIN summary s ON e.department = s.department WHERE e.salary > s.total / (SELECT COUNT(*) FROM employees WHERE department = e.department);",
      "LOCK TABLE users IN ACCESS EXCLUSIVE MODE; CREATE INDEX CONCURRENTLY idx_users_active_email ON users(active, email) WHERE active = true; ANALYZE users;",
      "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'app_production' AND state = 'idle' AND query_start < NOW() - INTERVAL '10 minutes';",
      "CREATE EVENT IF NOT EXISTS cleanup_logs ON SCHEDULE EVERY 1 DAY DO DELETE FROM logs WHERE created_at < NOW() - INTERVAL '90 days';",
      "SELECT jsonb_agg(jsonb_build_object('id', id, 'name', name, 'metadata', metadata)) as data FROM (SELECT * FROM items WHERE type = 'product' FOR UPDATE SKIP LOCKED) as locked_items;",
      "EXPLAIN (BUFFERS, ANALYZE, FORMAT JSON) SELECT * FROM orders o JOIN customers c ON o.customer_id = c.id WHERE o.created_at > NOW() - INTERVAL '30 days' AND c.region IN ('US', 'EU', 'APAC');",
    ]
  },
  html: {
    easy: [
      "<div>Hello</div>",
      "<p>Paragraph</p>",
      "<span>Text</span>",
      "<h1>Title</h1>",
      "<a href=\"/\">Link</a>",
      "<img src=\"image.jpg\" alt=\"\" />",
      "<ul><li>Item</li></ul>",
      "<input type=\"text\" />",
      "<button>Click</button>",
      "<br />",
      "<strong>Bold</strong>",
      "<em>Italic</em>",
      "<div class=\"container\"></div>",
      "<div id=\"header\"></div>",
      "<header><nav></nav></header>",
    ],
    medium: [
      "<div class=\"card\">\n  <img src=\"photo.jpg\" alt=\"Card image\" />\n  <h3>Title</h3>\n  <p>Description</p>\n</div>",
      "<form action=\"/submit\" method=\"POST\">\n  <label for=\"email\">Email:</label>\n  <input type=\"email\" id=\"email\" name=\"email\" required />\n  <button type=\"submit\">Submit</button>\n</form>",
      "<ul class=\"nav\">\n  <li><a href=\"/\">Home</a></li>\n  <li><a href=\"/about\">About</a></li>\n  <li><a href=\"/contact\">Contact</a></li>\n</ul>",
      "<div class=\"grid\">\n  <div class=\"col-4\">Column 1</div>\n  <div class=\"col-4\">Column 2</div>\n  <div class=\"col-4\">Column 3</div>\n</div>",
      "<table>\n  <thead><tr><th>Name</th><th>Age</th></tr></thead>\n  <tbody><tr><td>Alice</td><td>30</td></tr></tbody>\n</table>",
      "<video controls width=\"640\" height=\"480\">\n  <source src=\"movie.mp4\" type=\"video/mp4\" />\n  <track kind=\"captions\" src=\"captions.vtt\" srclang=\"en\" />\n</video>",
      "<meta name=\"description\" content=\"Page description\" />\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
      "<link rel=\"stylesheet\" href=\"styles.css\" />\n<script src=\"app.js\" defer></script>",
      "<input type=\"checkbox\" id=\"terms\" name=\"terms\" />\n<label for=\"terms\">I agree to the terms</label>",
      "<select name=\"country\">\n  <option value=\"us\">United States</option>\n  <option value=\"uk\">United Kingdom</option>\n</select>",
      "<figure>\n  <img src=\"chart.png\" alt=\"Sales chart\" />\n  <figcaption>Figure 1: Sales by quarter</figcaption>\n</figure>",
      "<details>\n  <summary>Click to expand</summary>\n  <p>Hidden content here...</p>\n</details>",
      "<svg width=\"100\" height=\"100\">\n  <circle cx=\"50\" cy=\"50\" r=\"40\" fill=\"blue\" />\n</svg>",
      "<div class=\"alert alert-success\" role=\"alert\">Success message</div>",
      "<nav aria-label=\"Main navigation\">\n  <ul><li><a href=\"#main\">Skip to content</a></li></ul>\n</nav>",
    ],
    hard: [
      "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n  <title>Page Title</title>\n  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\n  <link rel=\"canonical\" href=\"https://example.com/page\" />\n</head>\n<body>\n  <header class=\"site-header\">\n    <nav class=\"main-nav\" aria-label=\"Primary\">...</nav>\n  </header>\n  <main id=\"main-content\" role=\"main\">...</main>\n  <footer class=\"site-footer\">...</footer>\n</body>\n</html>",
      "<div class=\"modal\" id=\"login-modal\" role=\"dialog\" aria-labelledby=\"modal-title\" aria-modal=\"true\">\n  <div class=\"modal-dialog\">\n    <h2 id=\"modal-title\">Login</h2>\n    <form novalidate>\n      <div class=\"form-group\">\n        <label for=\"username\">Username</label>\n        <input type=\"text\" id=\"username\" autocomplete=\"username\" required aria-describedby=\"username-help\" />\n        <small id=\"username-help\" class=\"help-text\">Enter your email address</small>\n      </div>\n    </form>\n  </div>\n</div>",
      "<picture>\n  <source media=\"(min-width: 1200px)\" srcset=\"hero-large.jpg 2x, hero-medium.jpg 1x\" />\n  <source media=\"(min-width: 768px)\" srcset=\"hero-tablet.jpg\" />\n  <img src=\"hero-mobile.jpg\" alt=\"Hero image\" loading=\"eager\" />\n</picture>",
      "<script type=\"application/ld+json\">\n{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"Organization\",\n  \"name\": \"Company Name\",\n  \"url\": \"https://example.com\",\n  \"contactPoint\": {\n    \"@type\": \"ContactPoint\",\n    \"telephone\": \"+1-555-555-5555\",\n    \"contactType\": \"Customer Service\"\n  }\n}\n</script>",
      "<form class=\"checkout-form\" action=\"/checkout\" method=\"POST\">\n  <fieldset>\n    <legend>Shipping Address</legend>\n    <div class=\"address-fields\" role=\"group\" aria-labelledby=\"shipping-address\">\n      <input type=\"text\" name=\"street\" required pattern=\"[a-zA-Z0-9\\s]+\" />\n      <input type=\"text\" name=\"city\" required />\n      <select name=\"country\" required><option value=\"\">Select country</option></select>\n      <input type=\"text\" name=\"postal\" pattern=\"[A-Z0-9]{5,10}\" />\n    </div>\n  </fieldset>\n  <fieldset disabled>\n    <legend>Billing Address</legend>\n    ...\n  </fieldset>\n</form>",
      "<table class=\"data-table\">\n  <caption>Employee Directory</caption>\n  <colgroup>\n    <col span=\"1\" class=\"name-col\" />\n    <col span=\"1\" class=\"dept-col\" />\n    <col span=\"2\" class=\"contact-cols\" />\n  </colgroup>\n  <thead>\n    <tr><th scope=\"col\">Name</th><th scope=\"col\">Department</th><th scope=\"colgroup\" colSpan=\"2\">Contact</th></tr>\n  </thead>\n  <tbody>\n    <tr><td headers=\"name dept\">John</td><td>Engineering</td><td headers=\"contact email\">john@example.com</td><td headers=\"contact phone\">555-1234</td></tr>\n  </tbody>\n  <tfoot>\n    <tr><td colspan=\"4\">Total: 42 employees</td></tr>\n  </tfoot>\n</table>",
      "<div class=\"accordion\">\n  <div class=\"accordion-item\">\n    <button class=\"accordion-trigger\" aria-expanded=\"false\" aria-controls=\"section-1\">Section 1</button>\n    <div id=\"section-1\" class=\"accordion-panel\" role=\"region\" aria-hidden=\"true\">\n      <p>Content goes here...</p>\n    </div>\n  </div>\n  <div class=\"accordion-item\">\n    <button class=\"accordion-trigger\" aria-expanded=\"false\" aria-controls=\"section-2\">Section 2</button>\n    <div id=\"section-2\" class=\"accordion-panel\" role=\"region\" aria-hidden=\"true\">\n      <p>More content...</p>\n    </div>\n  </div>\n</div>",
      "<audio id=\"background-music\" preload=\"auto\" loop>\n  <source src=\"music.ogg\" type=\"audio/ogg\" />\n  <source src=\"music.mp3\" type=\"audio/mpeg\" />\n  <track kind=\"lyrics\" src=\"lyrics.vtt\" srclang=\"en\" default Your browser does not support the audio element />\n .\n</audio>",
      "<template id=\"card-template\">\n  <article class=\"card\" data-role=\"card\">\n    <header class=\"card-header\">\n      <img src=\"\" alt=\"\" class=\"card-image\" />\n      <h2 class=\"card-title\"></h2>\n    </header>\n    <div class=\"card-body\">\n      <slot name=\"description\"></slot>\n    </div>\n    <footer class=\"card-footer\">\n      <button type=\"button\" data-action=\"edit\">Edit</button>\n      <button type=\"button\" data-action=\"delete\" class=\"danger\">Delete</button>\n    </footer>\n  </article>\n</template>",
      "<canvas id=\"game-canvas\" width=\"800\" height=\"600\" role=\"img\" aria-label=\"Game canvas - use arrow keys to play\"></canvas>\n\n<!-- Shadow DOM example -->\n<template id=\"tooltip-template\">\n  <style>\n    :host { position: relative; display: inline-block; }\n    .tooltip { visibility: hidden; position: absolute; background: #333; color: #fff; padding: 4px 8px; border-radius: 4px; }\n    :host(:hover) .tooltip { visibility: visible; }\n  </style>\n  <slot></slot>\n  <div class=\"tooltip\"><slot name=\"tooltip-content\"></slot></div>\n</template>",
    ]
  },
  css: {
    easy: [
      ".container { }",
      "color: red;",
      "font-size: 16px;",
      "background-color: #fff;",
      "margin: 0;",
      "padding: 10px;",
      "display: flex;",
      "display: block;",
      "display: none;",
      "position: relative;",
      "position: absolute;",
      "width: 100%;",
      "height: 50px;",
      "border: 1px solid #ccc;",
      "border-radius: 4px;",
    ],
    medium: [
      ".card {\n  display: flex;\n  flex-direction: column;\n  gap: 1rem;\n  padding: 1.5rem;\n  border-radius: 8px;\n  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\n}",
      ".btn {\n  padding: 0.75rem 1.5rem;\n  font-weight: 600;\n  border: none;\n  border-radius: 6px;\n  cursor: pointer;\n  transition: all 0.2s ease;\n}",
      ".grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 1rem;\n}",
      "@media (max-width: 768px) {\n  .grid { grid-template-columns: 1fr; }\n}",
      ":root {\n  --primary: #3b82f6;\n  --secondary: #8b5cf6;\n  --spacing: 1rem;\n}",
      ".btn-primary {\n  background: linear-gradient(135deg, var(--primary), var(--secondary));\n}",
      ".nav {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}",
      ".input:focus {\n  outline: none;\n  border-color: var(--primary);\n  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.2);\n}",
      ".card:hover {\n  transform: translateY(-4px);\n  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\n}",
      ".modal {\n  position: fixed;\n  inset: 0;\n  display: grid;\n  place-items: center;\n  background: rgba(0, 0, 0, 0.5);\n}",
      ".sidebar {\n  position: sticky;\n  top: 1rem;\n  max-height: calc(100vh - 2rem);\n  overflow-y: auto;\n}",
      ".loader {\n  width: 48px;\n  height: 48px;\n  border: 4px solid #e5e7eb;\n  border-top-color: var(--primary);\n  border-radius: 50%;\n  animation: spin 1s linear infinite;\n}",
      ".text-ellipsis {\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n}",
      ".visually-hidden {\n  position: absolute;\n  width: 1px;\n  height: 1px;\n  padding: 0;\n  margin: -1px;\n  overflow: hidden;\n  clip: rect(0, 0, 0, 0);\n}",
      ".backdrop-blur {\n  backdrop-filter: blur(8px);\n  -webkit-backdrop-filter: blur(8px);\n}",
    ],
    hard: [
      ".grid-container {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(min(300px, 100%), 1fr));\n  grid-template-rows: masonry;\n  grid-auto-flow: dense;\n}",
      "@supports (container-type: inline-size) {\n  .card { container-type: inline-size; }\n  @container (min-width: 400px) {\n    .card { flex-direction: row; }\n  }\n}",
      ".container {\n  --gutter: clamp(1rem, 5vw, 2rem);\n  display: grid;\n  gap: var(--gutter);\n  padding: var(--gutter);\n}",
      "@layer base, components, utilities;\n@layer base {\n  html { scroll-behavior: smooth; }\n  :focus-visible { outline: 2px solid var(--primary); }\n}",
      ".skeleton {\n  background: linear-gradient(\n    110deg,\n    #ece9e6 8%,\n    #f5f2f0 18%,\n    #ece9e6 33%\n  );\n  background-size: 200% 100%;\n  animation: shimmer 1.5s linear infinite;\n}",
      ".scroll-snap-container {\n  scroll-snap-type: y mandatory;\n  overflow-y: scroll;\n  height: 100vh;\n}\n.scroll-snap-item {\n  scroll-snap-align: start;\n  scroll-snap-stop: always;\n}",
      ":root {\n  --spring-physics: cubic-bezier(0.175, 0.885, 0.32, 1.275);\n}\n.animated {\n  transition: transform var(--spring-physics);\n}",
      ".tooltip {\n  --tooltip-arrow-size: 8px;\n  position: absolute;\n  background: #1f2937;\n  color: white;\n  padding: 0.5rem 1rem;\n  border-radius: 0.375rem;\n}\n.tooltip::after {\n  content: '';\n  position: absolute;\n  border: var(--tooltip-arrow-size) solid transparent;\n  border-top-color: #1f2937;\n}",
      ".mask-image {\n  mask-image: url('mask.svg');\n  mask-mode: alpha;\n  -webkit-mask-image: url('mask.svg');\n  -webkit-mask-mode: alpha;\n}",
      "@property --progress {\n  syntax: '<percentage>';\n  inherits: false;\n  initial-value: 0%;\n}\n.animated-progress {\n  --progress: 50%;\n  background: linear-gradient(to right, var(--primary) var(--progress), transparent var(--progress));\n}",
      ".focus-ring:focus {\n  outline: none;\n}\n.focus-ring:focus-visible {\n  outline: 2px solid var(--primary);\n  outline-offset: 2px;\n}\n@supports (focus-visible: nth-child(1)) {\n  .focus-ring:focus { outline: none; }\n}",
      ".carousel {\n  display: flex;\n  overflow-x: auto;\n  scroll-snap-type: x mandatory;\n  scroll-behavior: smooth;\n  -webkit-overflow-scrolling: touch;\n}\n.carousel > * {\n  flex: 0 0 auto;\n  scroll-snap-align: start;\n}",
      ".aspect-ratio {\n  aspect-ratio: 16 / 9;\n  width: 100%;\n  object-fit: cover;\n}\n@supports not (aspect-ratio: 1) {\n  .aspect-ratio::before {\n    float: left;\n    padding-top: 56.25%;\n    content: '';\n  }\n}",
      "@layer {\n  .btn-primary {\n    background-color: oklch(70% 0.2 250);\n    color: oklch(100% 0 0);\n  }\n  @media (prefers-color-scheme: dark) {\n    .btn-primary {\n      background-color: oklch(60% 0.2 250);\n    }\n  }\n}",
      ".stagger-animation li {\n  animation: fadeIn 0.3s ease forwards;\n  opacity: 0;\n}\n.stagger-animation li:nth-child(1) { animation-delay: 0ms; }\n.stagger-animation li:nth-child(2) { animation-delay: 100ms; }\n.stagger-animation li:nth-child(3) { animation-delay: 200ms; }\n.stagger-animation li:nth-child(4) { animation-delay: 300ms; }\n.stagger-animation li:nth-child(5) { animation-delay: 400ms; }",
    ]
  },
};
